[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"
[tool.ruff]
select = ["E", "F", "B"]  # E: pycodestyle, F: pyflakes, B: bugbear

[tool.ruff.per-file-ignores]
"tests/*" = ["B020"]  # If you want to ignore this in test files
