[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"
[tool.ruff]
select = ["B"]  # B is for bugbear rules

[tool.ruff.per-file-ignores]
"tests/*" = ["B020"]  # If you want to ignore this in test files
